ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: mealie.local  # Change this to your domain or local hostname
        paths:
          - path: /
            pathType: Prefix
