apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: romulus-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.100.0/24
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: romulus-pool
  namespace: metallb-system
