apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-iii-upload-claim
spec:
  capacity:
    storage: 10Gi  # Must match the PVC request
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Ensure this matches PVC
  hostPath:
    path: "/var/mnt/firefly-data"  # Directory on the node

