apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-api-data
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual  # Ensure this matches the PV

