apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  labels:
    app: pihole
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  hostPath:
    path: "/var/mnt/pihole"  # Directory on the node
