apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: ghostfolio
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/var/mnt/postgres"
