apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostfolio-redis
  namespace: ghostfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      hostNetwork: true
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: env
              key: REDIS_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: env
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: env
              key: REDIS_PORT
        command: [ "sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\"" ]
---
apiVersion: v1
kind: Service
metadata:
  name: ghostfolio-redis
  namespace: ghostfolio
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
