apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: portfolio
spec:
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 80        # Exposes port 80 inside the cluster
      targetPort: 80  # Matches the container port
  type: ClusterIP  # No external IP needed
